### ISSUE TITLE
Dates for 'last week'

### ISSUE THREAD

**Issue by georgejkaye** [JonFreer/WMCycleData#4]
I assume that 'last week' means the past seven days, but perhaps putting the dates in would make this clearer? (if there is space to do so)

![image](https://github.com/JonFreer/WMCycleData/assets/7274805/c52c0126-7ca5-476f-b77d-840850d99c33)

**Comment by JonFreer** [comment]
Added in 9e3c9fb74f721abafa50381698b7bc54bda541e0

<img width="667" alt="image" src="https://github.com/JonFreer/WMCycleData/assets/30393324/48ca0669-dc37-455a-a335-670df5bbb4c6">

Thanks
