### ISSUE TITLE
Layout not always responsive when making window smaller

### ISSUE THREAD

**Issue by georgejkaye** [JonFreer/WMCycleData#5]
Sometimes when making the window less wide while on counter stats, the layout does not adjust and the 'number today', 'number last week'... boxes do not resize.

**Comment by georgejkaye** [comment]
![image](https://github.com/JonFreer/WMCycleData/assets/7274805/5a508791-31d7-4e2c-9c80-982e14e6a563)

**Comment by JonFreer** [comment]
Caused by the charts not respecting css-grids without setting grid-template-column. 

Should be fixed in c13b844fbb3b8ca580f8037fb8346d58ec91fdd4.

Thanks
